### ISSUE TITLE
How to work with Python 3.6?

### ISSUE THREAD

**Issue by guaigua** [101t/bigbluebutton-api-python#1]
ImportError: cannot import name 'quote_plus' 

File "/home/yoda/PycharmProjects/bigbluebutton-api-python/bigbluebutton_api_python/util/urlbuilder.py", line 9, in <module>
    from urllib.request import quote_plus
ImportError: cannot import name 'quote_plus'

Code:
Line 7 from urllib import quote_plus
Line 9 from urllib.request import quote_plus

Line 32 url += key + "=" + quote_plus(value) + "&"
Line 44 secret_str += key + "=" + quote_plus(value) + "&"

**Comment by 101t** [comment]
Hey,
It is based on Python version version:
```python
try:
    from urllib import quote  # Python 2.X
    from urllib import quote_plus
except ImportError:
    from urllib.parse import quote  # Python 3+
    from urllib.parse import quote_plus
```
You could also use the python compatibility wrapper [six](https://pythonhosted.org/six/) to handle this.
```python
from six.moves.urllib.parse import quote
```
That's all.
